version: '3.8'
services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres_gila
    volumes:
       - ./postgres-data:/var/lib/postgresql/data
       #- ./db/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
       #- ./db/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    ports:
      - '5432:5432'
volumes:
  db:
    driver: local